version: "1"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${API_CONNECTION_STRING}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
  db:
    image: mysql:8.0.30
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER}
    networks:
      - backend
    volumes:
      - db-data:/var/lib/backup/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  backend:
    driver: bridge

volumes:
  db-data:
